require: rubocop-rspec

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'resource', 'factory', 'define']
  Max: 30

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/migrate/*

HttpPositionalArguments:
  Enabled: true
  Exclude:
    - spec/**/*

AbcSize:
  Enabled: true
  Exclude:
    - db/migrate/*

DescribeClass:
  Exclude:
    - spec/system/**/*

Rails:
  Enabled: true

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - db/schema.rb
    - bin/*
